### ISSUE TITLE
Installation error during "make"

### ISSUE THREAD

**Issue by GiannakopoulosIlias** [EPTlib/eptlib#1]
Hi, 

During the make command I receive this error: 

```
Consolidate compiler generated dependencies of target EPTlib
[  4%] Building CXX object src/CMakeFiles/EPTlib.dir/version.cc.o
[  9%] Linking CXX shared library ../lib/libEPTlib.so
/usr/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
src/CMakeFiles/EPTlib.dir/build.make:368: recipe for target 'lib/libEPTlib.so' failed
make[2]: *** [lib/libEPTlib.so] Error 1
CMakeFiles/Makefile2:115: recipe for target 'src/CMakeFiles/EPTlib.dir/all' failed
make[1]: *** [src/CMakeFiles/EPTlib.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
```

Do you know how I can install properly the hdf5 library?

Thanks a lot!

**Comment by alessandroarduino** [comment]
Hi Ilias!

Sorry for the late reply, but I didn't get the notification. From now on, I should be more reactive.

If you reached that stage, it means that the cmake configuration succeeded. The command `cmake ..` executed in an empty build folder should tell you where the hdf5 library has been found and list all the package libs related to hdf5. Does that happen? If you can post all the output lines starting with `-- --[HDF5]`, it could be useful.

In some cases, it could be easier to compile EPTlib using the shared hdf5 library, instead of the static one. To do that, change the line in the CMakeLists.txt file in the project root directory from
`set(HDF5_USE_STATIC_LIBRARIES ON)`
to
`set(HDF5_USE_STATIC_LIBRARIES OFF)`

Usually, if you install the library from the repository of the used Linux distribution, it works well.
For example, in Arch Linux you can install it with
`sudo pacman -S hdf5`
In Debian or Ubuntu with
`sudo apt install libhdf5-dev`

**Comment by alessandroarduino** [comment]
Dear Ilias,

I reopened this issue because I faced it trying to compile EPTlib in Ubuntu 20.04 and the proposed solutions did not work.
I am not sure if it is a bug related to this particular version of Ubuntu or something else, however, when installing the HDF5 library with
```
sudo apt install libhdf5-dev
```
the shared library is installed with the name `libhdf5_serial.so`, whereas the linker `ld` searches for `libhdf5.so`. I solved this problem by creating a symbolic link as follow
```
cd /usr/lib/x86_64-linux-gnu
sudo ln -s libhdf5_serial.so libhdf5.so
```

Let me know if this works for you!
