### ISSUE TITLE
Ordering of dimensions in hdf5 dataset

### ISSUE THREAD

**Issue by pfuchs** [EPTlib/eptlib#3]
Using pythons h5py to interact with the hdf5 dataset gives a different ordering of dimension compared to the [mesh] "size" format in the input settings (they are flipped). Might be good to make a note of that in the readme, although I am surprised that this comes up as I was under the impression that C and hdf5 used the same row-major ordering.

**Comment by alessandroarduino** [comment]
This happens because of some choices in the design of h5py package and the row-major ordering of Python. A solution to the issue is already presented in the tutorial of EPTlib (https://eptlib.github.io/assets/tutorial/eptlib-tutorial.zip). However, to better highlight this aspect, I added a warning in the website, where the configuration file is described (https://eptlib.github.io/settings).
